### ISSUE TITLE
Xiaomi Redmi Note 12 Pro+ cannot boot using the repackaged image

### ISSUE THREAD

**Issue by Error-106** [arlept/mtklogo#5]
My device is able to successfully unpack using the following parameters
```
    - name: rubypro
    color_model: bgrabe
    formats:
    - { h: 2400, w: 1080}
    - { w: 45, h: 64 }
    - { w: 263, h: 2 }
    - { w: 263, h: 47 }
```
The following is the original image
[logo.zip](https://github.com/arlept/mtklogo/files/14420388/logo.zip)
